version: '3'

services:
  eps_db:
    image: postgres:latest
    env_file:
      - db/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
      - ./db/csv:/opt/eps

    