// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SerpsColumns holds the columns for the "serps" table.
	SerpsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "location", Type: field.TypeString},
		{Name: "contact_info", Type: field.TypeJSON},
		{Name: "key_words", Type: field.TypeJSON},
		{Name: "is_read", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "TIMESTAMP(0) WITH TIME ZONE"}},
	}
	// SerpsTable holds the schema information for the "serps" table.
	SerpsTable = &schema.Table{
		Name:       "serps",
		Columns:    SerpsColumns,
		PrimaryKey: []*schema.Column{SerpsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "serp_url_contact_info",
				Unique:  true,
				Columns: []*schema.Column{SerpsColumns[1], SerpsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SerpsTable,
	}
)

func init() {
	SerpsTable.Annotation = &entsql.Annotation{
		Table: "serps",
	}
}
