// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/karust/openserp/ent/searchquery"
)

// SearchQuery is the model entity for the SearchQuery schema.
type SearchQuery struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Query holds the value of the "query" field.
	Query string `json:"query,omitempty"`
	// Location holds the value of the "location" field.
	Location string `json:"location,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SearchQuery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case searchquery.FieldID:
			values[i] = new(sql.NullInt64)
		case searchquery.FieldQuery, searchquery.FieldLocation, searchquery.FieldLanguage:
			values[i] = new(sql.NullString)
		case searchquery.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SearchQuery fields.
func (sq *SearchQuery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case searchquery.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sq.ID = int(value.Int64)
		case searchquery.FieldQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query", values[i])
			} else if value.Valid {
				sq.Query = value.String
			}
		case searchquery.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				sq.Location = value.String
			}
		case searchquery.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				sq.Language = value.String
			}
		case searchquery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sq.CreatedAt = value.Time
			}
		default:
			sq.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SearchQuery.
// This includes values selected through modifiers, order, etc.
func (sq *SearchQuery) Value(name string) (ent.Value, error) {
	return sq.selectValues.Get(name)
}

// Update returns a builder for updating this SearchQuery.
// Note that you need to call SearchQuery.Unwrap() before calling this method if this SearchQuery
// was returned from a transaction, and the transaction was committed or rolled back.
func (sq *SearchQuery) Update() *SearchQueryUpdateOne {
	return NewSearchQueryClient(sq.config).UpdateOne(sq)
}

// Unwrap unwraps the SearchQuery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sq *SearchQuery) Unwrap() *SearchQuery {
	_tx, ok := sq.config.driver.(*txDriver)
	if !ok {
		panic("ent: SearchQuery is not a transactional entity")
	}
	sq.config.driver = _tx.drv
	return sq
}

// String implements the fmt.Stringer.
func (sq *SearchQuery) String() string {
	var builder strings.Builder
	builder.WriteString("SearchQuery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sq.ID))
	builder.WriteString("query=")
	builder.WriteString(sq.Query)
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(sq.Location)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(sq.Language)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sq.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SearchQueries is a parsable slice of SearchQuery.
type SearchQueries []*SearchQuery
